
services:
  worker:
    image: worker
    container_name: worker
    ports:
      - "4000:4000"
      - "5000:5000"
    environment:
      - WORKER_HTTP_PORT=4000
      - WORKER_GRPC_PORT=5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
